%define colors

loyolagreen = 1/255*[0,104,87];

loyolagray = 1/255*[200,200,200];

inesred=[0.8500, 0.3250, 0.0980];

inesblue=[0, 0.4470, 0.7410];

%%%%%ODEs for %%%%%%%

%y(1)=R resistant bac

%y(2)=S sensitive bac

%y(3)=A antibiotic

%y(4)=B b-lactamase


%Kr = number of R cells generated by unit of

%time

%Ks = number of S cells generated by unit of

%time

%Kar = number of R cells killed by each antiobiotic (A) molecule by unit of

%time

%Kas = number of S cells killed by each antiobiotic (A) molecule by unit of

%time

%Kba = number of antiobiotic (A) molecules degraded by unit of time by

%enzime

%Kb = number of enzime molecules excreted per unit of time per cell R

%Kl = number of enzyme molecules inside a R cell so when you have a R cell

%degraded you will be realizing B into the solution


%%Defining equations

%ode1 = diff(y1) == Kr*y(1) - Kar* y(3);

%ode2 = diff(y2) == Ks*y(2) - Kas* y(3);

%ode3 = diff(y3) == -Kba*y(4) ;

%ode4 = diff(y4) == Kb*y(1) + Kl * Kar* y(1) -0.5*y(4); %we added  term that depend

%on the death of R and a degradation constant of 50% per unit of time

%global Kr Ks Kas Kar Kb Kba A Kl

%odes = [ode1; ode2; ode3; ode4]

Kr = .021 ; % growth rate, /mins.

Ks = 1.15 * Kr; %growth rate, /mins.

Kas =  .05 ;% Kas = death rate of sensitive cells, /min, when A>1000.

Kar = .05 ; %death rate of resistant cells when A>1000, /min.

%Vmax = 1000;

A_Km = .00000067; %ug/uL, the michaelis-menton constant for ampicillin inactivation

%Klys = .13 ;  % we guess 1% is the lysis rate of R bac *MAKE AS A FUNCTION OF ANTIBIOTIC

Kba = .0029 ; % decay rate of antibiotic by enzyme, /min

Kl = .01 ; % concentration (ug/uL) of enzyme molecules inside a R cell so when you havea R cell

Kb = .001 ; % CONCENTRATION (ug/uL) of enzyme molecules excreted per unit of time per cell R

RA50 =  .6 ; % concentration of A requried for half-maximal killing effect of R

SA50 = .08 ; %concentration of A required for half-maximal killing effect of S

%NdR = .01 ; %decay of nutrients with R consumption

%NdS = .008 ; %decay of nutrients with S consumption

%===MONOD===%
%dF/dt = -(mmax * R * F)/(Y * (Ks + F)) -(mmax * R * F)/(Y * (Ks + F));
%dR/dt = (mmax * R * F)/ (Km + F) - (d * R);
%dR/dt = R (mmax * S)/ (Km + S) - (d * R);
mmaxR=Ks
mmaxS=Kr
Km=7000 %in ug/l we need to adapt this
d=0.0001 %dead per minute
Y=1
%f(5) = -NdR*y(1) - NdR*y(2);
%===========%
 

fode = @(t,y) [  y(1) * mmaxR * y(5)/ (Km + y(5)) - y(1) * Kar*y(3)/(RA50+y(3)) ;...
    y(2) * mmaxS * y(5)/(Km + y(5)) - y(2) * Kas*y(3)/(SA50+y(3)) ;...
    - Kba * y(4) * y(3) ; ...
    y(1) * Kb + Kl*y(1)* (Kar*y(3))/(RA50+y(3)) - .005*y(4) ;...
    -(mmaxR * y(1) * y(5) / (Y * (Km + y(5)))) - ( mmaxS * y(2) * y(5) / (Km + y(5)) )]

    %Kar*((1-y(1))/log10(y(3)))*y(1)

    %in f(2); ((y(4)/(Kba*y(1)))/(y(1)+y(2))) ?

    %f(1)= Kr*y(1)/(y(1)*log10(y(1)+y(2))) - (1+log10(y(3))/(Kar*y(1))) ?

tspan=0:1:1440;

 
y0=[500 ; 500 ; 1 ; 0 ; 10000]; %initial values

options = odeset('NonNegative',[1 2 3 4 5],'Events', @myEvents);%add the maximum amount of cells

[t,value]=ode45(fode,tspan,y0,options);

%{
figure(1); clf; hold on;

plot(t,value(:,1),'Color', loyolagreen)

plot(t,value(:,2),'Color', inesred)

plot(t,value(:,3),'Color',inesblue,"LineStyle","--")

plot(t,value(:,4),'Color', loyolagray,"LineStyle",'--')

legend('R bac', 'S bac', 'A antibiotic','\beta lact')

title('R, S, antibiotic and inhibitor levels vs time')

xlabel('time in minutes')

ylabel('Concentration (ug/uL')

 

figure(2); clf; hold on;

plot(t,value(:,1),'Color', loyolagreen)

plot(t,value(:,2),'Color', inesred)

legend('R bac', 'S bac' )

xlabel('time in hours')

ylabel('Concentration (ug/uL)')

 

figure(3); clf; hold on;

plot(t,value(:,3),'Color', loyolagreen)

legend('Antibiotic' )

xlabel('time in hours')

ylabel('Concentration (ug/uL)')

xlim([0 48]);


figure(4); clf; hold on;

plot(t,value(:,5),'Color', [0 0.7 0])

legend('food' )

xlabel('time in hours')

ylabel('Concentration (ug/uL)')

xlim([0 48]);

    %}

figure(5)
hold on
subplot(2,2,1)
plot(t,value(:,1),'Color', loyolagreen)
hold on
plot(t,value(:,2),'Color', inesred)
legend('R bac', 'S bac' )
xlabel('time in hours')
ylabel('Concentration (ug/uL)')
title("Bacteria")
subplot(2,2,2)
plot(t,value(:,3),'Color', loyolagreen)
title('Antibiotic' )
xlabel('time in hours')
ylabel('Concentration (ug/uL)')
subplot(2,2,3)
plot(t,value(:,5),'Color', [0 0.7 0])
title('food' )
xlabel('time in hours')
ylabel('Concentration (ug/uL)')
subplot(2,2,4)
plot(t,value(:,4),'Color', loyolagray,"LineStyle",'--')
title('\beta lactamase')
xlabel('time in hours')
ylabel('Concentration (ug/uL)')




fin_prop_plot_R=[]

fin_prop_plot_S=[]

ini_prop_plot_R=[]

ini_prop_plot_S=[]

e=0

for i=0:0.1:2

    for j=0:.1:1 %generate an initial proportion of 1000 total initial cells

       

        e=e+1  %generate a counter

       

        y0=[1000*j, 1000*(1-j), i,0, 10000]; %initial values

        [t,value]=ode45(fode,tspan,y0,options)


        %get initial prop

        ini_prop_plot_R(e)=j*100

        ini_prop_plot_S(e)=(1-j)*100


        %get final prop values

        x = find((value(:,1)+value(:,2))==max(value(:,1)+value(:,2)))

        t(x(1))
        

        fin_prop_plot_R(e)=value(x(1),1)/ (value(x(1),1)+value(x(1),2)) *100

        fin_prop_plot_S(e)=value(x(1),2)/ (value(x(1),1)+value(x(1),2)) *100

%{
        figure

        subplot(1,3,1)

        plot(t,value(:,1),'Color', loyolagreen)

        hold on

        plot(t,value(:,2),'Color', inesred)

        legend('R bac', 'S bac' )

        xlabel('time in minutes')

        ylabel('molecules/ml')

        subplot(1,3,2)

        plot(t,value(:,3),'Color',loyolagreen,"LineStyle","--")

        legend('Antibiotic' )

        xlabel('time in minutes')

        ylabel('molecules/ml')

        xlim([0 10])

        subplot(1,3,3)

        plot(t,value(:,4),'Color', loyolagray,"LineStyle",'--')

        legend('\_beta lactamase' )

        xlabel('time in minutes')

        ylabel('molecules/ml')

        sgtitle(["Antibiotic = ",num2str(i),"initial S = ",num2str((1-j)*100),"initial  = ",num2str(j*100)])

        hold off
%}
    end


end


C = {[0.2 0.8 0.8],'k','b','r','g','y',[.5 .6 .7],[.8 .2 .6],[1 0.2 0.2],[1 0.5 0],[0.2 0 0],inesblue,inesred,loyolagreen,loyolagray,[1 0.5 0],[1 0.5 0.5],[0.5 0.9 0],[0.5 0.9 0.5],[0.8 0.5 0.2],[0.2 0.2 0.8],[0.3 0.9 1],[0.3 0.4 0.9],[1 0.4 0.2],[0.7 1 0]};
length(ini_prop_plot_R)

figure(100)
hold on
e=0

for k=1:10:(length(ini_prop_plot_R)-10)


    e=e+1

    plot(ini_prop_plot_R(k:k+10),fin_prop_plot_R(k:k+10),"-o",'color',C{e})

  

end

xlabel('initial Res frac')

ylabel('final Res frac')

legend(strsplit(num2str(1:0.1:3)))


 
